<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <PublishSingleFile>true</PublishSingleFile>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>TowerToHeaven</RootNamespace>
        <OutputName>Tower to Heaven</OutputName>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="Content/**" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="TowerToHeaven.bmp" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="fnalibs/**" CopyToOutputDirectory="PreserveNewest" />
        
        <ProjectReference Include="../FNA/FNA.Core.csproj">
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </ProjectReference>
        
        <ProjectReference Include="../FontStashSharp/src/XNA/FontStashSharp.FNA.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Content\Sounds\" />
    </ItemGroup>

</Project>
